server:
  port: 8080
  
spring:
  security:
    oauth2:
      client:
        provider:
          demo:
            issuer-uri: https://login.plaintext.ch/auth/realms/demo
        registration:
          demo:
            redirect-uri: http://localhost:8080/login/oauth2/code/demo
            scope: openid,profile,email
            client-id: demo
            client-secret: URLCtcDI7L3HIhZbcmKKVfP1R4NclRZl
joinfaces:
  jsf:
    stages:
      project-stage: Development
  primefaces:
    cacheProvider: org.primefaces.cache.DefaultCacheProvider
    uploader: native
    theme: saga

logging:
  level:
    root: INFO
    
management:
  endpoints:
    web:
      exposure:
        include: health,info