name: 'mvn release'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'release version: Ex: 0.1.0'
        required: true
        type: string
      next-snapshot:
        description: 'next snapshot version: Ex: 0.2.0-SNAPSHOT'
        required: true
        type: string

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'adopt'

    - name: 'do the release'
      id: release
      run: |
        
        mvn versions:set -DnewVersion=${{ inputs.version }}
        mvn versions:commit
        
        mvn versions:set -DnewVersion=${{ inputs.next-snapshot }}
        mvn versions:commit

      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
